### PR TITLE
Add apng animation support

### PR DESCRIPTION
**Pull request by djempuiw**
- Apply apng patch to PNG lib, from here: https://github.com/rickytan/libpng-apng
- Extend png loader functionality to load animated apng files. If number of frames is not dividable by directions, load as single animation.
- PNG_BLEND_OP_OVER is not supported, warn if used, other blending and frame disposals are implemented.

### CODE REVIEW

**Comment by APAmk2** [comment]
You sure it's needed? Because engine already has `.fofrm` format, where you describing FPS, frames count and frame names as file paths.

**Comment by djempuiw** [comment]
> You sure it's needed? Because engine already has `.fofrm` format, where you describing FPS, frames count and frame names as file paths.

Ah, I missed that somehow :P I guess, main advantage is that it's easier to view apng, as most modern browsers and image viewers support it. Can view directly on github for example.

**Comment by cvet** [comment]
Okay, I apply code soon, need only make some code cleanup, you use too few empty line breaks.

**Comment by cvet** [comment]
And add information about APNG to README.md, ThirdParty/README.md
* [PNG/APNG](https://github.com/rickytan/libpng-apng) - png/apng image loader
* PNG/APNG - [libpng1616](http://www.libpng.org/pub/png/libpng.html) [libpng-apng](https://github.com/rickytan/libpng-apng)

**Comment by cvet** [comment]
Run clang-format
https://github.com/cvet/fonline/actions/runs/9620456707/job/26548371248

**Comment by cvet** [comment]
cd .../Source
clang-format -i Applications/*.* Client/*.* Common/*.* Common/AngelScriptExt/*.* Server/*.* Tools/*.* Scripting/*.* Frontend/*.* Singleplayer/*.* Scripting/AngelScript/*.fos Tests/*.*

**Comment by cvet** [comment]
And use clang-format 15.

**Comment by djempuiw** [comment]
Can add check for directions number via tEXt field if you think it's better.

**Pull request merged**
